version: '3.4'

services:
  temps:
    build:
      context: .
    environment:
      - "TEMPS_FAKE_OUTDOOR_TEMP=46.7"
      - "TEMPS_TAG_LIST_SECRET=dev"
      - "TEMPS_PUBLIC_PATH=/live/public"
    volumes:
      - ./public:/live/public

  nginx:
    image: nginx:1.15.8
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '8070:8070'
    depends_on:
      - temps
