#!/bin/bash

set -e

echo Building image...
docker build --rm --tag spraints-temps .

echo Starting spraints-temps...
docker rm -f spraints-temps >&/dev/null || true
docker run -d --restart=unless-stopped \
  --env-file .env \
  --env TEMPS_LISTEN_ADDR=:8080 \
  --name spraints-temps \
  spraints-temps
